services:
  - type: web
    name: product-page-project
    env: node
    nodeVersion: 20.11.1
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: VITE_API_URL
        value: https://product-page-project.onrender.com/api
    healthCheckPath: /api
    autoDeploy: true 