services:
  - type: web
    name: product-page-project
    env: node
    rootDir: .
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 